### ISSUE TITLE
Создать CRUD Frontend для навыков специалиста

### ISSUE THREAD

**Issue by nurbek19** [ESDP-JS-1/garnet#17]
### Для того чтобы создавать резюме нам нужно иметь справочник навыков

1. Сделать форму добавления навыка. Написать фунцию для создания навыка
2. Функция для получения навыков. Сохранить их в store и сделать отображение.
3. Написать функцию для редактирования навыка
4. Написать функцию для удаления навыка

**Comment by zako16** [comment]
Это все фронтэнд? В апи разве есть этот функционал?

**Comment by K073** [comment]
> Это все фронтэнд? В апи разве есть этот функционал?

в апи уже есть

**Comment by 1xzc1** [comment]
Зкрыт по причине сходтства с 10 таском

**Comment by zako16** [comment]
ок, если в апи есть, пожалуйста исправляйте меня в отчетах :3 если я неправа/забыла. В след раз буду записывать чтобы не забыть и отчет был правдивым
