### ISSUE TITLE
Развернуть приложение на демонстрационном сервере

### ISSUE THREAD

**Issue by K073** [ESDP-JS-1/garnet#23]
Для демонстрации продукта нужно запусть Api и React приложение на выделеном сервере
### 6 часов на выполнение

**Comment by 1xzc1** [comment]
План работ:
Настройка nginx установка pm2, git, node, mongo.
создание ползователя и пароля
Запуск приложения и проверка

**Comment by 1xzc1** [comment]
Закончил развертывание 
потрачено 6 часов

**Comment by zako16** [comment]
А демостранция извне доступна? Всмысле внешняя ссылка есть, чтобы посмотреть? Спасибо.

**Comment by 1xzc1** [comment]
Ссылку в телеграм скину если надо

Отправлено с моего телефона на Windows 10

От: Meerim Zhanuzakova
Отправлено: четверг, 5 июля 2018 г. в 16:39
Кому: ESDP-JS-1/garnet
Копия: Bugaev Egor; State change
Тема: Re: [ESDP-JS-1/garnet] Развернуть приложение на демонстрационном сервере (#23)

А демостранция извне доступна? Всмысле внешняя ссылка есть, чтобы посмотреть? Спасибо

**Comment by zako16** [comment]
Да, было бы круто, спасибо
