### ISSUE TITLE
Создать базовую структуру "Back-End api"

### ISSUE THREAD

**Issue by K073** [ESDP-JS-1/garnet#3]
необходимо создать\подключить
*.gitignore
*fixtures(empty)
*nodemon
*express
*mongoose

**Comment by K073** [comment]
Нужно изменить Readme, не описано как запускать fixture, какой то db.template 
> Copy db.template.json to db.json

хотя его даже нету в проекте
нужно написать что для запуска нужна mongo, т.к без нее ничего не стартанет

**Comment by 1xzc1** [comment]
Update readme
