### ISSUE TITLE
API для создания категории навыка

### ISSUE THREAD

**Issue by nurbek19** [ESDP-JS-1/garnet#7]
## Для создания резюме нам нужно навыки специалиста

1. Создать модель для категории
2. Создать роут для создания категории

**Comment by nurbek19** [comment]
Потратил 20 минут

**Comment by K073** [comment]
Нужно создать Fixture c 3 вложеностями для модели SkillCategory

**Comment by nurbek19** [comment]
Потратил 20 минут
